### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by davelab6** [DunwichType/DTF_Proofs#1]
Please add a license file; probably CC-0 or MIT

**Comment by DunwichType** [comment]
The SIL Open Font license license is already there as LICENSE, referred to in README, and in the fonts themselves. Is this just Google changing its mind about licensing (IIRC they wanted SIL or Apache in the past).

Best,

James Puckett
Dunwich Type Founders
http://www.dunwichtype.com
917-846-9948

**Comment by davelab6** [comment]
I saw only one file in this repo

**Comment by DunwichType** [comment]
In https://github.com/DunwichType/RhodiumLibre ?

A screenshot of everything I’m seeing in there is attached. 

Best,

James Puckett
Dunwich Type Founders
http://www.dunwichtype.com
917-846-9948

**Comment by davelab6** [comment]
No, in this repo! :)

**Comment by DunwichType** [comment]
Sorry, I assumed that you were referring to the Google project! I always forget about this proofs repo. I’ll try to throw a bunch of new files in and add a license before I go to sleep. Thanks for reminding me.

Best,

James Puckett
Dunwich Type Founders
http://www.dunwichtype.com
917-846-9948

**Comment by DunwichType** [comment]
I fixed it. For some reason Github required me to use its web interface to add the LICENSE file instead of just picking up the file in the repo.
